// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace EmployeeTestProject.UIMapFiles.UIMapForAbsenceUIClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public partial class UIMapForAbsenceUI
    {
        
        /// <summary>
        /// AssertMethod1
        /// </summary>
        public void AssertMethod1()
        {
            #region Variable Declarations
            HtmlComboBox uIEmployeeComboBox = this.UIAbsenceWindowsInternWindow.UIAbsenceDocument.UIEmployeeComboBox;
            #endregion

            // Verify that 'Employee' combo box's property 'SelectedItem' is not equal to 'null'
            Assert.IsNotNull(uIEmployeeComboBox.SelectedItem);
        }
        
        #region Properties
        public UIAbsenceWindowsInternWindow UIAbsenceWindowsInternWindow
        {
            get
            {
                if ((this.mUIAbsenceWindowsInternWindow == null))
                {
                    this.mUIAbsenceWindowsInternWindow = new UIAbsenceWindowsInternWindow();
                }
                return this.mUIAbsenceWindowsInternWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIAbsenceWindowsInternWindow mUIAbsenceWindowsInternWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIAbsenceWindowsInternWindow : BrowserWindow
    {
        
        public UIAbsenceWindowsInternWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Absence";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Absence");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIAbsenceDocument UIAbsenceDocument
        {
            get
            {
                if ((this.mUIAbsenceDocument == null))
                {
                    this.mUIAbsenceDocument = new UIAbsenceDocument(this);
                }
                return this.mUIAbsenceDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIAbsenceDocument mUIAbsenceDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIAbsenceDocument : HtmlDocument
    {
        
        public UIAbsenceDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Absence";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Absence/Insert.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:3062/Absence/Insert.aspx?EmployeeID=113";
            this.WindowTitles.Add("Absence");
            #endregion
        }
        
        #region Properties
        public HtmlComboBox UIEmployeeComboBox
        {
            get
            {
                if ((this.mUIEmployeeComboBox == null))
                {
                    this.mUIEmployeeComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIEmployeeComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "ContentPlaceHolder1_FormView1_ctl04_ctl07___Employee_DropDownList1";
                    this.mUIEmployeeComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "ctl00$ContentPlaceHolder1$FormView1$ctl04$ctl07$__Employee$DropDownList1";
                    this.mUIEmployeeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIEmployeeComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = "Employee";
                    this.mUIEmployeeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIEmployeeComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "2";
                    this.mUIEmployeeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "DDDropDown";
                    this.mUIEmployeeComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "id=ContentPlaceHolder1_FormView1_ctl04_c";
                    this.mUIEmployeeComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUIEmployeeComboBox.WindowTitles.Add("Absence");
                    #endregion
                }
                return this.mUIEmployeeComboBox;
            }
        }
        #endregion
        
        #region Fields
        private HtmlComboBox mUIEmployeeComboBox;
        #endregion
    }
}
