gcc -o relax relax.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe relax        
gcc -o relax2 relax2.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe relax2       
gcc -o relax3 relax3.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe relax3
gcc -o thrdd thrdd.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe thrdd        
gcc -o thrfuz thrfuz.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe thrfuz       
gcc -o thrglh thrglh.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe thrglh       
gcc -o thris thris.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe thris        
gcc -o thrjoh thrjoh.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe thrjoh       
gcc -o thrkapur thrkapur.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe thrkapur     
gcc -o thrlap thrlap.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe thrlap       
gcc -o thrme thrme.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe thrme        
gcc -o thrmean thrmean.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe thrmean      
gcc -o thrmulis thrmulis.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe thrmulis     
gcc -o thrpct thrpct.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe thrpct       
gcc -o thrpun thrpun.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe thrpun       
gcc -o twopeaks twopeaks.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe twopeaks     

