//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("HumanResourceModel", "FK_Absence_Employee", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EmployeeMaintenance.Employee), "Absence", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EmployeeMaintenance.Absence), true)]
[assembly: EdmRelationshipAttribute("HumanResourceModel", "FK_EmergencyContact_Employee", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EmployeeMaintenance.Employee), "EmergencyContact", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EmployeeMaintenance.EmergencyContact), true)]

#endregion

namespace EmployeeMaintenance
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HumanResourceEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HumanResourceEntities object using the connection string found in the 'HumanResourceEntities' section of the application configuration file.
        /// </summary>
        public HumanResourceEntities() : base("name=HumanResourceEntities", "HumanResourceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HumanResourceEntities object.
        /// </summary>
        public HumanResourceEntities(string connectionString) : base(connectionString, "HumanResourceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HumanResourceEntities object.
        /// </summary>
        public HumanResourceEntities(EntityConnection connection) : base(connection, "HumanResourceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Absence> Absence
        {
            get
            {
                if ((_Absence == null))
                {
                    _Absence = base.CreateObjectSet<Absence>("Absence");
                }
                return _Absence;
            }
        }
        private ObjectSet<Absence> _Absence;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EmergencyContact> EmergencyContact
        {
            get
            {
                if ((_EmergencyContact == null))
                {
                    _EmergencyContact = base.CreateObjectSet<EmergencyContact>("EmergencyContact");
                }
                return _EmergencyContact;
            }
        }
        private ObjectSet<EmergencyContact> _EmergencyContact;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employee
        {
            get
            {
                if ((_Employee == null))
                {
                    _Employee = base.CreateObjectSet<Employee>("Employee");
                }
                return _Employee;
            }
        }
        private ObjectSet<Employee> _Employee;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Absence EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAbsence(Absence absence)
        {
            base.AddObject("Absence", absence);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EmergencyContact EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmergencyContact(EmergencyContact emergencyContact)
        {
            base.AddObject("EmergencyContact", emergencyContact);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employee EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployee(Employee employee)
        {
            base.AddObject("Employee", employee);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HumanResourceModel", Name="Absence")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Absence : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Absence object.
        /// </summary>
        /// <param name="absenceID">Initial value of the AbsenceID property.</param>
        /// <param name="employeeID">Initial value of the EmployeeID property.</param>
        /// <param name="max_Casual_Leave">Initial value of the Max_Casual_Leave property.</param>
        /// <param name="max_Privilege_Leave">Initial value of the Max_Privilege_Leave property.</param>
        public static Absence CreateAbsence(global::System.String absenceID, global::System.Int32 employeeID, global::System.Decimal max_Casual_Leave, global::System.Decimal max_Privilege_Leave)
        {
            Absence absence = new Absence();
            absence.AbsenceID = absenceID;
            absence.EmployeeID = employeeID;
            absence.Max_Casual_Leave = max_Casual_Leave;
            absence.Max_Privilege_Leave = max_Privilege_Leave;
            return absence;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AbsenceID
        {
            get
            {
                return _AbsenceID;
            }
            set
            {
                if (_AbsenceID != value)
                {
                    OnAbsenceIDChanging(value);
                    ReportPropertyChanging("AbsenceID");
                    _AbsenceID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("AbsenceID");
                    OnAbsenceIDChanged();
                }
            }
        }
        private global::System.String _AbsenceID;
        partial void OnAbsenceIDChanging(global::System.String value);
        partial void OnAbsenceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                OnEmployeeIDChanging(value);
                ReportPropertyChanging("EmployeeID");
                _EmployeeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmployeeID");
                OnEmployeeIDChanged();
            }
        }
        private global::System.Int32 _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.Int32 value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Max_Casual_Leave
        {
            get
            {
                return _Max_Casual_Leave;
            }
            set
            {
                OnMax_Casual_LeaveChanging(value);
                ReportPropertyChanging("Max_Casual_Leave");
                _Max_Casual_Leave = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Max_Casual_Leave");
                OnMax_Casual_LeaveChanged();
            }
        }
        private global::System.Decimal _Max_Casual_Leave;
        partial void OnMax_Casual_LeaveChanging(global::System.Decimal value);
        partial void OnMax_Casual_LeaveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Max_Privilege_Leave
        {
            get
            {
                return _Max_Privilege_Leave;
            }
            set
            {
                OnMax_Privilege_LeaveChanging(value);
                ReportPropertyChanging("Max_Privilege_Leave");
                _Max_Privilege_Leave = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Max_Privilege_Leave");
                OnMax_Privilege_LeaveChanged();
            }
        }
        private global::System.Decimal _Max_Privilege_Leave;
        partial void OnMax_Privilege_LeaveChanging(global::System.Decimal value);
        partial void OnMax_Privilege_LeaveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Casual_Leave_Taken
        {
            get
            {
                return _Casual_Leave_Taken;
            }
            set
            {
                OnCasual_Leave_TakenChanging(value);
                ReportPropertyChanging("Casual_Leave_Taken");
                _Casual_Leave_Taken = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Casual_Leave_Taken");
                OnCasual_Leave_TakenChanged();
            }
        }
        private Nullable<global::System.Decimal> _Casual_Leave_Taken;
        partial void OnCasual_Leave_TakenChanging(Nullable<global::System.Decimal> value);
        partial void OnCasual_Leave_TakenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Privilege_Leave_Taken
        {
            get
            {
                return _Privilege_Leave_Taken;
            }
            set
            {
                OnPrivilege_Leave_TakenChanging(value);
                ReportPropertyChanging("Privilege_Leave_Taken");
                _Privilege_Leave_Taken = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Privilege_Leave_Taken");
                OnPrivilege_Leave_TakenChanged();
            }
        }
        private Nullable<global::System.Decimal> _Privilege_Leave_Taken;
        partial void OnPrivilege_Leave_TakenChanging(Nullable<global::System.Decimal> value);
        partial void OnPrivilege_Leave_TakenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Remaining_Casual_Leave
        {
            get
            {
                return _Remaining_Casual_Leave;
            }
            set
            {
                OnRemaining_Casual_LeaveChanging(value);
                ReportPropertyChanging("Remaining_Casual_Leave");
                _Remaining_Casual_Leave = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Remaining_Casual_Leave");
                OnRemaining_Casual_LeaveChanged();
            }
        }
        private Nullable<global::System.Decimal> _Remaining_Casual_Leave;
        partial void OnRemaining_Casual_LeaveChanging(Nullable<global::System.Decimal> value);
        partial void OnRemaining_Casual_LeaveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Remaining_Privilege_Leave
        {
            get
            {
                return _Remaining_Privilege_Leave;
            }
            set
            {
                OnRemaining_Privilege_LeaveChanging(value);
                ReportPropertyChanging("Remaining_Privilege_Leave");
                _Remaining_Privilege_Leave = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Remaining_Privilege_Leave");
                OnRemaining_Privilege_LeaveChanged();
            }
        }
        private Nullable<global::System.Decimal> _Remaining_Privilege_Leave;
        partial void OnRemaining_Privilege_LeaveChanging(Nullable<global::System.Decimal> value);
        partial void OnRemaining_Privilege_LeaveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HumanResourceModel", "FK_Absence_Employee", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("HumanResourceModel.FK_Absence_Employee", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("HumanResourceModel.FK_Absence_Employee", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("HumanResourceModel.FK_Absence_Employee", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("HumanResourceModel.FK_Absence_Employee", "Employee", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HumanResourceModel", Name="EmergencyContact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EmergencyContact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EmergencyContact object.
        /// </summary>
        /// <param name="employeeID">Initial value of the EmployeeID property.</param>
        /// <param name="contact_Name">Initial value of the Contact_Name property.</param>
        public static EmergencyContact CreateEmergencyContact(global::System.Int32 employeeID, global::System.String contact_Name)
        {
            EmergencyContact emergencyContact = new EmergencyContact();
            emergencyContact.EmployeeID = employeeID;
            emergencyContact.Contact_Name = contact_Name;
            return emergencyContact;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                if (_EmployeeID != value)
                {
                    OnEmployeeIDChanging(value);
                    ReportPropertyChanging("EmployeeID");
                    _EmployeeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EmployeeID");
                    OnEmployeeIDChanged();
                }
            }
        }
        private global::System.Int32 _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.Int32 value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Contact_Name
        {
            get
            {
                return _Contact_Name;
            }
            set
            {
                if (_Contact_Name != value)
                {
                    OnContact_NameChanging(value);
                    ReportPropertyChanging("Contact_Name");
                    _Contact_Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Contact_Name");
                    OnContact_NameChanged();
                }
            }
        }
        private global::System.String _Contact_Name;
        partial void OnContact_NameChanging(global::System.String value);
        partial void OnContact_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Address_1
        {
            get
            {
                return StructuralObject.GetValidValue(_Address_1);
            }
            set
            {
                OnAddress_1Changing(value);
                ReportPropertyChanging("Address_1");
                _Address_1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address_1");
                OnAddress_1Changed();
            }
        }
        private global::System.Byte[] _Address_1;
        partial void OnAddress_1Changing(global::System.Byte[] value);
        partial void OnAddress_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address_2
        {
            get
            {
                return _Address_2;
            }
            set
            {
                OnAddress_2Changing(value);
                ReportPropertyChanging("Address_2");
                _Address_2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address_2");
                OnAddress_2Changed();
            }
        }
        private global::System.String _Address_2;
        partial void OnAddress_2Changing(global::System.String value);
        partial void OnAddress_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Phone_1
        {
            get
            {
                return _Phone_1;
            }
            set
            {
                OnPhone_1Changing(value);
                ReportPropertyChanging("Phone_1");
                _Phone_1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Phone_1");
                OnPhone_1Changed();
            }
        }
        private Nullable<global::System.Int32> _Phone_1;
        partial void OnPhone_1Changing(Nullable<global::System.Int32> value);
        partial void OnPhone_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Phone_2
        {
            get
            {
                return _Phone_2;
            }
            set
            {
                OnPhone_2Changing(value);
                ReportPropertyChanging("Phone_2");
                _Phone_2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Phone_2");
                OnPhone_2Changed();
            }
        }
        private Nullable<global::System.Int32> _Phone_2;
        partial void OnPhone_2Changing(Nullable<global::System.Int32> value);
        partial void OnPhone_2Changed();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HumanResourceModel", "FK_EmergencyContact_Employee", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("HumanResourceModel.FK_EmergencyContact_Employee", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("HumanResourceModel.FK_EmergencyContact_Employee", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("HumanResourceModel.FK_EmergencyContact_Employee", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("HumanResourceModel.FK_EmergencyContact_Employee", "Employee", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HumanResourceModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="employeeID">Initial value of the EmployeeID property.</param>
        /// <param name="first_Name">Initial value of the First_Name property.</param>
        /// <param name="last_Name">Initial value of the Last_Name property.</param>
        public static Employee CreateEmployee(global::System.Int32 employeeID, global::System.String first_Name, global::System.String last_Name)
        {
            Employee employee = new Employee();
            employee.EmployeeID = employeeID;
            employee.First_Name = first_Name;
            employee.Last_Name = last_Name;
            return employee;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                if (_EmployeeID != value)
                {
                    OnEmployeeIDChanging(value);
                    ReportPropertyChanging("EmployeeID");
                    _EmployeeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EmployeeID");
                    OnEmployeeIDChanged();
                }
            }
        }
        private global::System.Int32 _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.Int32 value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String First_Name
        {
            get
            {
                return _First_Name;
            }
            set
            {
                OnFirst_NameChanging(value);
                ReportPropertyChanging("First_Name");
                _First_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("First_Name");
                OnFirst_NameChanged();
            }
        }
        private global::System.String _First_Name;
        partial void OnFirst_NameChanging(global::System.String value);
        partial void OnFirst_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Last_Name
        {
            get
            {
                return _Last_Name;
            }
            set
            {
                OnLast_NameChanging(value);
                ReportPropertyChanging("Last_Name");
                _Last_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Last_Name");
                OnLast_NameChanged();
            }
        }
        private global::System.String _Last_Name;
        partial void OnLast_NameChanging(global::System.String value);
        partial void OnLast_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Middle_Name
        {
            get
            {
                return _Middle_Name;
            }
            set
            {
                OnMiddle_NameChanging(value);
                ReportPropertyChanging("Middle_Name");
                _Middle_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Middle_Name");
                OnMiddle_NameChanged();
            }
        }
        private global::System.String _Middle_Name;
        partial void OnMiddle_NameChanging(global::System.String value);
        partial void OnMiddle_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Department
        {
            get
            {
                return _Department;
            }
            set
            {
                OnDepartmentChanging(value);
                ReportPropertyChanging("Department");
                _Department = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Department");
                OnDepartmentChanged();
            }
        }
        private global::System.String _Department;
        partial void OnDepartmentChanging(global::System.String value);
        partial void OnDepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Occupation
        {
            get
            {
                return _Occupation;
            }
            set
            {
                OnOccupationChanging(value);
                ReportPropertyChanging("Occupation");
                _Occupation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Occupation");
                OnOccupationChanged();
            }
        }
        private global::System.String _Occupation;
        partial void OnOccupationChanging(global::System.String value);
        partial void OnOccupationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private Nullable<global::System.Int32> _Phone;
        partial void OnPhoneChanging(Nullable<global::System.Int32> value);
        partial void OnPhoneChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HumanResourceModel", "FK_Absence_Employee", "Absence")]
        public EntityCollection<Absence> Absences
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Absence>("HumanResourceModel.FK_Absence_Employee", "Absence");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Absence>("HumanResourceModel.FK_Absence_Employee", "Absence", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HumanResourceModel", "FK_EmergencyContact_Employee", "EmergencyContact")]
        public EntityCollection<EmergencyContact> EmergencyContacts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EmergencyContact>("HumanResourceModel.FK_EmergencyContact_Employee", "EmergencyContact");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EmergencyContact>("HumanResourceModel.FK_EmergencyContact_Employee", "EmergencyContact", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
