// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace EmployeeTestProject.UIMapFiles.UIMapforModule1Classes
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public partial class UIMapforModule1
    {
        
        /// <summary>
        /// AssertMethod1
        /// </summary>
        public void AssertMethod1()
        {
            #region Variable Declarations
            HtmlEdit uIPhone_1Edit = this.UIEmergencyContactWindWindow.UIEmergencyContactDocument.UIPhone_1Edit;
            #endregion

            // Verify that 'Phone_1' text box's property 'Text' is not equal to 'null'
            Assert.IsNotNull(uIPhone_1Edit.Text);
        }
        
        #region Properties
        public UIEmergencyContactWindWindow UIEmergencyContactWindWindow
        {
            get
            {
                if ((this.mUIEmergencyContactWindWindow == null))
                {
                    this.mUIEmergencyContactWindWindow = new UIEmergencyContactWindWindow();
                }
                return this.mUIEmergencyContactWindWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIEmergencyContactWindWindow mUIEmergencyContactWindWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIEmergencyContactWindWindow : BrowserWindow
    {
        
        public UIEmergencyContactWindWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Emergency Contact";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Emergency Contact");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIEmergencyContactDocument UIEmergencyContactDocument
        {
            get
            {
                if ((this.mUIEmergencyContactDocument == null))
                {
                    this.mUIEmergencyContactDocument = new UIEmergencyContactDocument(this);
                }
                return this.mUIEmergencyContactDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIEmergencyContactDocument mUIEmergencyContactDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIEmergencyContactDocument : HtmlDocument
    {
        
        public UIEmergencyContactDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Emergency Contact";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/EmergencyContact/Insert.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:3062/EmergencyContact/Insert.aspx";
            this.WindowTitles.Add("Emergency Contact");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIPhone_1Edit
        {
            get
            {
                if ((this.mUIPhone_1Edit == null))
                {
                    this.mUIPhone_1Edit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPhone_1Edit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ContentPlaceHolder1_FormView1_ctl04_ctl05___Phone_1_TextBox1";
                    this.mUIPhone_1Edit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$ContentPlaceHolder1$FormView1$ctl04$ctl05$__Phone_1$TextBox1";
                    this.mUIPhone_1Edit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Phone_1";
                    this.mUIPhone_1Edit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPhone_1Edit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPhone_1Edit.FilterProperties[HtmlEdit.PropertyNames.Class] = "DDTextBox";
                    this.mUIPhone_1Edit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=ContentPlaceHolder1_FormView1_ctl04_c";
                    this.mUIPhone_1Edit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "10";
                    this.mUIPhone_1Edit.WindowTitles.Add("Emergency Contact");
                    #endregion
                }
                return this.mUIPhone_1Edit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIPhone_1Edit;
        #endregion
    }
}
