gcc -o recp recp.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe recp
gcc -o recv recv.c lib.c -lm   
coff2exe -s c:\gnu\bin\go32.exe recv   
gcc -o recc recc.c lib.c -lm   
coff2exe -s c:\gnu\bin\go32.exe recc   
gcc -o nnlearn nnlearn.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe nnlearn   
gcc -o nnclass nnclass.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe nnclass   
gcc -o nncvt nncvt.c lib.c -lm
coff2exe -s c:\gnu\bin\go32.exe nncvt   
